version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn api.main_pipeline:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    working_dir: /app
    command: streamlit run interface/interfaz_pipeline.py --server.port 8501
    volumes:
      - .:/app
    restart: always
